---
# tasks file for hoplacloud.mikrotik-create-profile
- name: Init vars
  set_fact:
    passphrase: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"
    password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,hexdigits') }}"

- name: Création du compte
  community.routeros.command:
    commands:
          - /ppp secret add name={{ username }} service=ovpn password={{ passphrase }} profile=openvpn

- name: Création du template de certificat pour le secret
  community.routeros.command:
    commands:
          - /certificate add name="{{ username }}-template" common-name={{ username }} days-valid={{ days_valid }}

- name: Signature avec le certificat
  community.routeros.command:
    commands:
          - /certificate sign "{{ username }}-template" ca={{ awx_inventory_name }}_CA name={{ username }}

- name: Export dans les fichier et création du mdp
  community.routeros.command:
    commands:
          - /certificate export-certificate {{ username }} export-passphrase={{ password }}

- name: Génération fichier .ovpn
  copy:
    dest: "/etc/test.ovpn"
    content: |
      client
      dev tun
      proto tcp-client
      remote {{ mikrotik_pub_ip }} 1194
      nobind
      persist-key
      persist-tun
      cipher AES-256-CBC
      auth SHA1
      pull
      verb 1
      mute 3

      auth-user-pass auth.cfg

      ca {{tower_inventory_name}}_CA.crt
      cert cert_export_{{username}}.crt
      key cert_export_{{username}}.key
      route
- name: Génération fichier .cfg
  copy:
    dest: "/etc/test.cfg"
    content: |
      {{username}}
      {{passphrase}}

- name: Upload to hoplacloud S3
  community.aws.s3_sync:
    bucket: ho-corp-ovpnconf
    file_root: /etc/test.ovpn
<<<<<<< HEAD
    ec2_url: https://s3.fr-east-1.pub.hopla.cloud
=======
    ec2_url: https://fr-east-1.pub.hopla.cloud:13000/v3/users/3f2444e7abcb45e28a6ee741e6b99e05/credentials/OS-EC2/68503e2ce3274fdd955bdd549b9b293d
>>>>>>> bd6532c069c3d3f33546574f9bc58cacb5ab23b9
