---
# tasks file for hoplacloud.mikrotik-create-profile
- name: Init vars
  set_fact:
    passphrase: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"
    password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,hexdigits') }}"

- name: Vérification que le profil n'existe pas
  routeros_command:
    commands:
          - /ppp secret print count-only where name={{username}}
  register: profile

- name: Arrêt du job si le profil est présent
  fail:
    msg: Un profil avec le même nom d'utilisateur est déja présent, vérifiez sur WinBox.
  when: profile is search("1")

- name: Création du compte
  community.routeros.command:
    commands:
          - /ppp secret add name={{ username }} service=ovpn password={{ passphrase }} profile=openvpn
  when: profile is search("0")

- name: Création du template de certificat pour le secret
  community.routeros.command:
    commands:
          - /certificate add name="{{ username }}-template" common-name={{ username }} days-valid={{ days_valid }}

- name: Signature avec le certificat
  community.routeros.command:
    commands:
          - /certificate sign "{{ username }}-template" ca={{ awx_inventory_name }}_CA name={{ username }}

- name: Export dans les fichier et création du mdp
  community.routeros.command:
    commands:
          - /certificate export-certificate {{ username }} export-passphrase={{ password }}

- name: Génération fichier .ovpn
  copy:
    dest: "/etc/{{tower_inventory_name}}_{{username}}.ovpn"
    content: |
      client
      dev tun
      proto tcp-client
      remote {{ mikrotik_pub_ip }} 1194
      nobind
      persist-key
      persist-tun
      cipher AES-256-CBC
      auth SHA1
      pull
      verb 1
      mute 3

      auth-user-pass auth.cfg

      ca {{tower_inventory_name}}_CA.crt
      cert cert_export_{{username}}.crt
      key cert_export_{{username}}.key
      route
- name: Génération fichier .cfg
  copy:
    dest: "/etc/{{tower_inventory_name}}_{{username}}.cfg"
    content: |
      {{username}}
      {{passphrase}}

- name: Upload to hoplacloud S3 ovpnconf
  s3_sync:
    bucket: ho-corp-ovpnconf
    file_root: /etc/{{tower_inventory_name}}_{{username}}.ovpn
    ec2_url: https://s3-fr-east-1.pub.hopla.cloud

- name: Upload to hoplacloud S3 configuration file
  s3_sync:
    bucket: ho-corp-ovpnconf
    file_root: /etc/{{tower_inventory_name}}_{{username}}.cfg
    ec2_url: https://s3-fr-east-1.pub.hopla.cloud
