---
# tasks file for hoplacloud.mikrotik-create-profile
- name: Init vars
  set_fact:
    passphrase: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"
    password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,hexdigits') }}"

- debug:
    msg: "Randomly generated password is : {{ password }} and passphrase is : {{ passphrase }}"
