---
# tasks file for hoplacloud.mikrotik-create-profile
- name: Init vars
  set_fact:
    passphrase: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"
    password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,hexdigits') }}"

- debug:
    msg: "Randomly generated password is : {{ password }} and passphrase is : {{ passphrase }}"

- name: Création du compte
  community.routeros.command:
    commands:
          - /ppp secret add name={{ username }} service=ovpn password={{ passphrase }} profile=openvpn

- name: Création du template de certificat pour le secret
  community.routeros.command:
    commands:
          - /certificate add name="{{ username }}-template" common-name={{ username }} days-valid={{ days_valid }}

- name: Signature avec le certificat
  community.routeros.command:
    commands:
          - /certificate sign "{{ username }}-template" ca={{ id_client }}_CA name={{ username }}

- name: Export dans les fichier et création du mdp
  community.routeros.command:
    commands:
          - /certificate export-certificate {{ username }} export-passphrase={{ password }}

- name: Génération fichier .ovpn
  copy:
    dest: "/etc/test.ovpn"
    content: |
      client
      dev tun
      proto tcp-client
      remote {{openstack.metadata.ssh_pub_ip}} 1194
      nobind
      persist-key
      persist-tun
      cipher AES-256-CBC
      auth SHA1
      pull
      verb 1
      mute 3

      auth-user-pass auth.cfg

      ca {{id_client}}_CA.crt
      cert cert_export_{{username}}.crt
      key cert_export_{{username}}.key
      route
- name: Génération fichier .ovpn
  copy:
    dest: "/etc/test.cfg"
    content: |
      {{username}}
      {{passphrase}}
